# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven
 workflow_dispatch
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean test

  selenium:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest  # Using the Selenium Standalone Chrome image
        options: --shm-size=2g
        ports:
          - 4444:4444  # Exposing the Selenium server port

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to the version you're using

      - name: Install dependencies
        run: |
          npm install  # Install dependencies from package.json

      - name: Run Selenium tests
        run: |
          npm test  # This will run the "test" script in your package.json, which should run your Selenium tests
        env:
          SELENIUM_HOST: "localhost"
          SELENIUM_PORT: "4444"

    
